version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    network_mode: host

  backend:
    image: ziyak8856532/api:latest
   
    depends_on:
      - mongo
    

  frontend:
    image: ziyak8856532/client:latest
    environment:
      - NODE_ENV=development
    network_mode: host

volumes:
  mongo-data:
    driver: local
